import '@servicenow/sdk/global';
import { Table, StringColumn, Record } from '@servicenow/sdk/core';

// -- Travel Request table
// Stores travel approval requests created by the agent
export const x_snc_travel_a7t2p_travel_request = Table({
    name: 'x_snc_travel_a7t2p_travel_request',
    label: 'Travel Request',
    accessible_from: 'public',
    actions: ['create', 'read', 'update', 'delete'],
    allow_web_service_access: true,
    display: 'request_number',
    schema: {
        request_number: StringColumn({ label: 'Request Number', maxLength: 40 }),
        requester_name: StringColumn({ label: 'Requester Name', maxLength: 200 }),
        requester_email: StringColumn({ label: 'Requester Email', maxLength: 200 }),
        travel_type: StringColumn({ label: 'Travel Type', maxLength: 40 }),
        destination: StringColumn({ label: 'Destination', maxLength: 200 }),
        departure_date: StringColumn({ label: 'Departure Date', maxLength: 40 }),
        return_date: StringColumn({ label: 'Return Date', maxLength: 40 }),
        business_purpose: StringColumn({ label: 'Business Purpose', maxLength: 2000 }),
        estimated_airfare: StringColumn({ label: 'Estimated Airfare', maxLength: 40 }),
        flight_class_requested: StringColumn({ label: 'Flight Class Requested', maxLength: 40 }),
        estimated_flight_hours: StringColumn({ label: 'Estimated Flight Hours', maxLength: 40 }),
        estimated_accommodation_per_night: StringColumn({ label: 'Estimated Accommodation Per Night', maxLength: 40 }),
        estimated_accommodation_nights: StringColumn({ label: 'Estimated Accommodation Nights', maxLength: 40 }),
        ground_transport_type: StringColumn({ label: 'Ground Transport Type', maxLength: 100 }),
        estimated_ground_transport: StringColumn({ label: 'Estimated Ground Transport', maxLength: 40 }),
        estimated_meals_total: StringColumn({ label: 'Estimated Meals Total', maxLength: 40 }),
        client_entertainment_required: StringColumn({ label: 'Client Entertainment Required', maxLength: 10 }),
        estimated_entertainment: StringColumn({ label: 'Estimated Entertainment', maxLength: 40 }),
        total_estimated_cost: StringColumn({ label: 'Total Estimated Cost', maxLength: 40 }),
        approval_status: StringColumn({ label: 'Approval Status', maxLength: 40 }),
        policy_assessment: StringColumn({ label: 'Policy Assessment', maxLength: 4000 }),
        approval_routing: StringColumn({ label: 'Approval Routing', maxLength: 200 }),
        created_by_agent: StringColumn({ label: 'Created By Agent', maxLength: 10 }),
    },
});

// -- Seed data: 3 sample travel requests

export const travel_request_1 = Record({
    $id: Now.ID['travel-request-tr0001'],
    table: 'x_snc_travel_a7t2p_travel_request',
    data: {
        request_number: 'TR0001',
        requester_name: 'Sarah Chen',
        requester_email: 'sarah.chen@company.com',
        travel_type: 'domestic',
        destination: 'Melbourne, Australia',
        departure_date: '2026-05-15',
        return_date: '2026-05-17',
        business_purpose: 'Client workshop for Q3 platform rollout',
        estimated_airfare: '450',
        flight_class_requested: 'economy',
        estimated_flight_hours: '1.5',
        estimated_accommodation_per_night: '220',
        estimated_accommodation_nights: '2',
        ground_transport_type: 'rideshare',
        estimated_ground_transport: '80',
        estimated_meals_total: '250',
        client_entertainment_required: 'false',
        estimated_entertainment: '0',
        total_estimated_cost: '1220',
        approval_status: 'approved',
        policy_assessment: 'All items within policy. Domestic travel, economy class, accommodation under $250/night cap.',
        approval_routing: 'manager',
        created_by_agent: 'true',
    },
});

export const travel_request_2 = Record({
    $id: Now.ID['travel-request-tr0002'],
    table: 'x_snc_travel_a7t2p_travel_request',
    data: {
        request_number: 'TR0002',
        requester_name: 'James Park',
        requester_email: 'james.park@company.com',
        travel_type: 'international',
        destination: 'Tokyo, Japan',
        departure_date: '2026-06-02',
        return_date: '2026-06-08',
        business_purpose: 'Partner summit and joint roadmap planning with NTT Data',
        estimated_airfare: '6200',
        flight_class_requested: 'business',
        estimated_flight_hours: '9.5',
        estimated_accommodation_per_night: '280',
        estimated_accommodation_nights: '6',
        ground_transport_type: 'public_transport',
        estimated_ground_transport: '150',
        estimated_meals_total: '750',
        client_entertainment_required: 'true',
        estimated_entertainment: '400',
        total_estimated_cost: '9180',
        approval_status: 'pending_vp',
        policy_assessment: 'International travel. Business class requested - flight is 9.5 hours (over 6hr threshold), premium economy is auto-eligible, business class requires VP approval. Accommodation at $280/night exceeds $250 USD cap - exception needed. Client entertainment at $400 for estimated 4 attendees ($100/person) is within cap. Extended stay - recommend serviced apartment options.',
        approval_routing: 'vp',
        created_by_agent: 'true',
    },
});

export const travel_request_3 = Record({
    $id: Now.ID['travel-request-tr0003'],
    table: 'x_snc_travel_a7t2p_travel_request',
    data: {
        request_number: 'TR0003',
        requester_name: 'Priya Sharma',
        requester_email: 'priya.sharma@company.com',
        travel_type: 'domestic',
        destination: 'Perth, Australia',
        departure_date: '2026-05-20',
        return_date: '2026-05-21',
        business_purpose: 'Internal team meeting',
        estimated_airfare: '1800',
        flight_class_requested: 'business',
        estimated_flight_hours: '5',
        estimated_accommodation_per_night: '350',
        estimated_accommodation_nights: '1',
        ground_transport_type: 'rental_car',
        estimated_ground_transport: '200',
        estimated_meals_total: '125',
        client_entertainment_required: 'false',
        estimated_entertainment: '0',
        total_estimated_cost: '2475',
        approval_status: 'pending_review',
        policy_assessment: 'POLICY FLAGS: (1) Business class requested for a 5-hour domestic flight - policy allows economy only for flights under 6 hours. VP approval required for business class. (2) Accommodation at $350/night exceeds $250 AUD domestic cap. (3) Internal meeting - consider whether virtual meeting could replace travel per sustainability guidelines.',
        approval_routing: 'vp',
        created_by_agent: 'true',
    },
});

// -- Additional realistic seed data

export const travel_request_4 = Record({
    $id: Now.ID['travel-request-tr0004'],
    table: 'x_snc_travel_a7t2p_travel_request',
    data: {
        request_number: 'TR0004',
        requester_name: 'David Liu',
        requester_email: 'david.liu@company.com',
        travel_type: 'domestic',
        destination: 'Brisbane, Australia',
        departure_date: '2026-05-28',
        return_date: '2026-05-30',
        business_purpose: 'Sales enablement workshop for ANZ regional team — presenting new product demo and closing strategy for Q3 pipeline',
        estimated_airfare: '380',
        flight_class_requested: 'economy',
        estimated_flight_hours: '2',
        estimated_accommodation_per_night: '195',
        estimated_accommodation_nights: '2',
        ground_transport_type: 'rideshare',
        estimated_ground_transport: '65',
        estimated_meals_total: '250',
        client_entertainment_required: 'false',
        estimated_entertainment: '0',
        total_estimated_cost: '1085',
        approval_status: 'approved',
        policy_assessment: 'All items within policy guidelines. Domestic economy class, accommodation $195/night under $250 cap.',
        approval_routing: 'manager',
        created_by_agent: 'true',
    },
});

export const travel_request_5 = Record({
    $id: Now.ID['travel-request-tr0005'],
    table: 'x_snc_travel_a7t2p_travel_request',
    data: {
        request_number: 'TR0005',
        requester_name: 'Emma Wilson',
        requester_email: 'emma.wilson@company.com',
        travel_type: 'international',
        destination: 'London, United Kingdom',
        departure_date: '2026-06-15',
        return_date: '2026-06-22',
        business_purpose: 'ServiceNow Knowledge 26 conference — presenting keynote on AI automation and attending partner breakout sessions',
        estimated_airfare: '5800',
        flight_class_requested: 'premium_economy',
        estimated_flight_hours: '22',
        estimated_accommodation_per_night: '240',
        estimated_accommodation_nights: '7',
        ground_transport_type: 'public_transport',
        estimated_ground_transport: '180',
        estimated_meals_total: '875',
        client_entertainment_required: 'true',
        estimated_entertainment: '350',
        total_estimated_cost: '8885',
        approval_status: 'pending_vp',
        policy_assessment: '[REQUIRED] International travel requires VP-level approval. [OK] Premium economy permitted for 22-hour flight. [REQUIRED] Client entertainment requires manager approval. Accommodation $240/night within $250 USD cap.',
        approval_routing: 'vp',
        created_by_agent: 'true',
    },
});

export const travel_request_6 = Record({
    $id: Now.ID['travel-request-tr0006'],
    table: 'x_snc_travel_a7t2p_travel_request',
    data: {
        request_number: 'TR0006',
        requester_name: 'Marcus Thompson',
        requester_email: 'marcus.thompson@company.com',
        travel_type: 'international',
        destination: 'San Francisco, United States',
        departure_date: '2026-07-07',
        return_date: '2026-07-11',
        business_purpose: 'Quarterly business review with Salesforce partnership team and joint go-to-market planning for APAC expansion',
        estimated_airfare: '7200',
        flight_class_requested: 'business',
        estimated_flight_hours: '14',
        estimated_accommodation_per_night: '320',
        estimated_accommodation_nights: '4',
        ground_transport_type: 'rideshare',
        estimated_ground_transport: '200',
        estimated_meals_total: '500',
        client_entertainment_required: 'true',
        estimated_entertainment: '600',
        total_estimated_cost: '9780',
        approval_status: 'pending_vp',
        policy_assessment: '[REQUIRED] International travel requires VP approval. [REQUIRED] Business class requires VP approval — 14-hour flight qualifies for premium economy auto-approval. [FLAG] Accommodation $320/night exceeds $250 USD cap. [REQUIRED] Client entertainment $600 requires manager approval. [FLAG] Entertainment exceeds $100/person cap if fewer than 6 attendees.',
        approval_routing: 'vp',
        created_by_agent: 'true',
    },
});

export const travel_request_7 = Record({
    $id: Now.ID['travel-request-tr0007'],
    table: 'x_snc_travel_a7t2p_travel_request',
    data: {
        request_number: 'TR0007',
        requester_name: 'Anika Patel',
        requester_email: 'anika.patel@company.com',
        travel_type: 'domestic',
        destination: 'Adelaide, Australia',
        departure_date: '2026-06-10',
        return_date: '2026-06-11',
        business_purpose: 'On-site technical implementation support for SA Health EHR migration — go-live week',
        estimated_airfare: '320',
        flight_class_requested: 'economy',
        estimated_flight_hours: '2.5',
        estimated_accommodation_per_night: '185',
        estimated_accommodation_nights: '1',
        ground_transport_type: 'rental_car',
        estimated_ground_transport: '95',
        estimated_meals_total: '125',
        client_entertainment_required: 'false',
        estimated_entertainment: '0',
        total_estimated_cost: '725',
        approval_status: 'approved',
        policy_assessment: 'All items within policy. Economy class domestic, accommodation under cap, rental car mid-size.',
        approval_routing: 'manager',
        created_by_agent: 'true',
    },
});

export const travel_request_8 = Record({
    $id: Now.ID['travel-request-tr0008'],
    table: 'x_snc_travel_a7t2p_travel_request',
    data: {
        request_number: 'TR0008',
        requester_name: 'Tom Nguyen',
        requester_email: 'tom.nguyen@company.com',
        travel_type: 'international',
        destination: 'Seoul, South Korea',
        departure_date: '2026-07-20',
        return_date: '2026-07-27',
        business_purpose: 'Samsung SDS integration sprint — 5-day co-development workshop for unified ITSM connector build',
        estimated_airfare: '4200',
        flight_class_requested: 'premium_economy',
        estimated_flight_hours: '10',
        estimated_accommodation_per_night: '210',
        estimated_accommodation_nights: '7',
        ground_transport_type: 'public_transport',
        estimated_ground_transport: '120',
        estimated_meals_total: '875',
        client_entertainment_required: 'false',
        estimated_entertainment: '0',
        total_estimated_cost: '6665',
        approval_status: 'approved',
        policy_assessment: '[REQUIRED] International travel requires VP approval. [OK] Premium economy permitted for 10-hour flight. Accommodation $210/night within $250 USD cap. Extended stay — serviced apartment recommended.',
        approval_routing: 'vp',
        created_by_agent: 'true',
    },
});

export const travel_request_9 = Record({
    $id: Now.ID['travel-request-tr0009'],
    table: 'x_snc_travel_a7t2p_travel_request',
    data: {
        request_number: 'TR0009',
        requester_name: 'Sarah Chen',
        requester_email: 'sarah.chen@company.com',
        travel_type: 'international',
        destination: 'Jakarta, Indonesia',
        departure_date: '2026-08-11',
        return_date: '2026-08-14',
        business_purpose: 'Bank Mandiri RFP response — in-person presentation and solution architecture walkthrough with CTO office',
        estimated_airfare: '3100',
        flight_class_requested: 'economy',
        estimated_flight_hours: '7',
        estimated_accommodation_per_night: '180',
        estimated_accommodation_nights: '3',
        ground_transport_type: 'rideshare',
        estimated_ground_transport: '90',
        estimated_meals_total: '375',
        client_entertainment_required: 'true',
        estimated_entertainment: '250',
        total_estimated_cost: '4355',
        approval_status: 'pending_manager',
        policy_assessment: '[REQUIRED] International travel requires VP approval. [OK] Premium economy eligible for 7-hour flight but economy selected — within policy. [REQUIRED] Client entertainment requires manager approval. Accommodation $180/night within $250 USD cap.',
        approval_routing: 'vp',
        created_by_agent: 'true',
    },
});

export const travel_request_10 = Record({
    $id: Now.ID['travel-request-tr0010'],
    table: 'x_snc_travel_a7t2p_travel_request',
    data: {
        request_number: 'TR0010',
        requester_name: 'James Park',
        requester_email: 'james.park@company.com',
        travel_type: 'domestic',
        destination: 'Canberra, Australia',
        departure_date: '2026-06-23',
        return_date: '2026-06-25',
        business_purpose: 'Federal government compliance audit — presenting security posture review to Department of Home Affairs',
        estimated_airfare: '290',
        flight_class_requested: 'economy',
        estimated_flight_hours: '1',
        estimated_accommodation_per_night: '230',
        estimated_accommodation_nights: '2',
        ground_transport_type: 'rideshare',
        estimated_ground_transport: '55',
        estimated_meals_total: '250',
        client_entertainment_required: 'false',
        estimated_entertainment: '0',
        total_estimated_cost: '1055',
        approval_status: 'approved',
        policy_assessment: 'All items within policy. Domestic economy, accommodation $230/night under $250 cap.',
        approval_routing: 'manager',
        created_by_agent: 'true',
    },
});
